"""Autogenerated via `poetry run update-colors palette.svg`."""
import enum


__all__ = ["Color"]


class Color(enum.StrEnum):
    black0 = "#13161b"
    black1 = "#1a1d23"
    black2 = "#22272f"
    black3 = "#2f3541"
    black4 = "#404859"
    black5 = "#4d576a"
    blue0 = "#364c8c"
    blue1 = "#4f6aba"
    blue2 = "#7b8fcc"
    cyan0 = "#366f8c"
    cyan1 = "#4f97ba"
    cyan2 = "#7bb1cc"
    green0 = "#51744e"
    green1 = "#709d6c"
    green2 = "#94b691"
    purple0 = "#674e74"
    purple1 = "#8d6c9d"
    purple2 = "#a991b6"
    red0 = "#843e44"
    red1 = "#b15960"
    red2 = "#c48288"
    white0 = "#bcc3d2"
    white1 = "#d4d9e2"
    white2 = "#edeff3"
    white3 = "#f6f7f9"
    white4 = "#fcfcfd"
    white5 = "#fff"
    yellow0 = "#8d7034"
    yellow1 = "#bd974c"
    yellow2 = "#cdb179"
