"""Autogenerated via `poetry run update-colors palette.svg`."""
import enum


__all__ = ["Color"]


class Color(enum.StrEnum):
    black0 = "#13171b"
    black1 = "#1a1f23"
    black2 = "#22292f"
    black3 = "#2f3841"
    black4 = "#404d59"
    black5 = "#4d5c6a"
    blue0 = "#406182"
    blue1 = "#5b85ae"
    blue2 = "#84a3c2"
    cyan0 = "#408282"
    cyan1 = "#5baeae"
    cyan2 = "#84c2c2"
    green0 = "#4e744e"
    green1 = "#6c9d6c"
    green2 = "#91b691"
    purple0 = "#674e74"
    purple1 = "#8d6c9d"
    purple2 = "#a991b6"
    red0 = "#843e44"
    red1 = "#b15960"
    red2 = "#c48288"
    white0 = "#bcc7d2"
    white1 = "#d4dbe2"
    white2 = "#edf0f3"
    white3 = "#f6f7f9"
    white4 = "#fcfcfd"
    white5 = "#fff"
    yellow0 = "#8d7034"
    yellow1 = "#bd974c"
    yellow2 = "#cdb179"
